// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Runninghill.Database;

#nullable disable

namespace Runninghill.Database.Migrations.Postgres
{
    /// <summary>
    /// Records the Postgres EF model after adding the nullable search-key column; used by migration
    /// tooling.
    /// </summary>
    [DbContext(typeof(PostgresContext))]
    [Migration("20261008141628_AddSearchKey")]
    partial class AddSearchKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Runninghill.Database.SchemaRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("schema_info", "runninghill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Version = 2
                        });
                });

            modelBuilder.Entity("Runninghill.Database.SentenceRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4050)
                        .HasColumnType("character varying(4050)")
                        .HasColumnName("text");

                    b.PrimitiveCollection<long[]>("WordIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("word_ids");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("sentences_request_id");

                    b.ToTable("sentences", "runninghill");
                });

            modelBuilder.Entity("Runninghill.Database.WordRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("NormalizedWord")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_word")
                        .UseCollation("C");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Id")
                        .HasDatabaseName("words_type_id");

                    b.HasIndex("Word", "Type")
                        .IsUnique()
                        .HasDatabaseName("words_word_type");

                    b.ToTable("words", "runninghill");
                });
#pragma warning restore 612, 618
        }
    }
}
