#!/usr/bin/env python3
"""Validate paired company palettes and generate the web's pre-start default colours."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    """Check every theme before packaging; reject executable CSS and incomplete light/dark pairs."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--generate', action='store_true')
    args = parser.parse_args()
    themes = {}
    for path in sorted((ROOT / 'themes').glob('*.json')):
        assert re.fullmatch(r'[A-Za-z0-9_-]+_(light|dark)', path.stem), f'Invalid theme filename: {path.name}'
        colors = json.loads(path.read_text(encoding='utf-8'))['colors']
        assert all(re.fullmatch(r'[A-Za-z]+', key) and isinstance(value, str) and re.fullmatch(r'#[A-Fa-f0-9]{6}', value) for key, value in colors.items()), f'Invalid colour in {path.name}'
        themes[path.stem] = colors
    required = themes['Runninghill_light'].keys()
    for name, colors in themes.items():
        assert colors.keys() == required, f'Colour roles in {name} differ from Runninghill_light'
        company, mode = name.rsplit('_', 1)
        assert company + ('_dark' if mode == 'light' else '_light') in themes, f'Missing partner for {name}'
    css = '/* Generated by scripts/check-themes.py --generate. Colours are also embedded in both clients. */\n'
    for mode in ['light', 'dark']:
        css += (':root' if mode == 'light' else ':root[data-brightness="dark"]') + ' {\n'
        css += ''.join(f'    --{key}:{value};\n' for key, value in themes['Runninghill_' + mode].items())
        css += f'    color-scheme:{mode};\n}}\n'
    output = ROOT / 'src/Clients/Runninghill.Web/wwwroot/theme-defaults.css'
    if args.generate:
        output.write_text(css, encoding='utf-8')
    else:
        assert output.read_text(encoding='utf-8') == css, 'Run python scripts/check-themes.py --generate after editing the default themes.'
    print(f'Verified {len(themes)} theme files with {len(required)} colour roles each.')


if __name__ == '__main__':
    main()
