#!/usr/bin/env python3
"""Verify complete translations and format arguments; optionally regenerate lookup/bootstrap files."""
import argparse
import json
import re
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
RESOURCES = ROOT / "src/Runninghill.Contracts/Resources"
LANGUAGES = {"en-ZA": "", "af-ZA": "_af_ZA", "xh-ZA": "_xh_ZA", "zu-ZA": "_zu_ZA", "tn-ZA": "_tn_ZA"}


def read(suffix):
    """Read compiled-resource inputs without requiring a .NET SDK."""
    entries = ET.parse(RESOURCES / f"Text{suffix}.resx").findall("data")
    result = {entry.attrib["name"]: entry.findtext("value") for entry in entries}
    assert len(result) == len(entries), f"Duplicate key in Text{suffix}.resx"
    return result


def generated_files(catalogs):
    """Build cached C# keys and the small dictionary needed before Blazor has loaded."""
    english = catalogs["en-ZA"]
    source = """// Generated from Resources/Text.resx by scripts/check-localization.py --generate.
namespace Runninghill.Contracts;

/// <summary>Maps English source messages to stable resource keys without hashing on each render.</summary>
public static partial class AppText
{
    private static readonly IReadOnlyDictionary<string, string> Keys = new Dictionary<string, string>(StringComparer.Ordinal)
    {
"""
    for key, message in english.items():
        source += f"        [{json.dumps(message, ensure_ascii=False)}] = {json.dumps(key)},\n"
    source += "    };\n}\n"
    bootstrap = {}
    labels = [
        "Loading Runninghill…",
        "Runninghill could not finish loading. Reload the page. If this continues, try a private browser window and share the diagnostic details with support.",
        "Reload", "This page could not be displayed.",
        "Reload the page. Unsaved changes may be lost. Before repeating a save, check whether it already succeeded.",
        "A file needed by this page could not be loaded. Check your connection and reload. If it continues, share the file name and diagnostic details with support.",
        "This browser cannot run the app. Update your browser and make sure JavaScript and WebAssembly are allowed, then reload.",
        "Diagnostic details", "Copy diagnostic details", "Diagnostic details copied.",
        "Could not copy automatically. Select and copy the diagnostic details below.",
        "Share these details with support. Do not include your access token."
    ]
    for language, entries in catalogs.items():
        bootstrap[language] = [entries[next(key for key, value in english.items() if value == label)] for label in labels]
    javascript = "// Generated by scripts/check-localization.py --generate.\n"
    javascript += "(() => {\n  const messages = " + json.dumps(bootstrap, ensure_ascii=False, indent=2) + ";\n"
    javascript += "  const labels = " + json.dumps(labels, ensure_ascii=False) + ";\n"
    javascript += """  const normalize = value => Object.keys(messages).find(code => code.toLowerCase() === String(value).toLowerCase()) || 'en-ZA';
  const apply = language => {
    document.documentElement.lang = language;
    const text = messages[language];
    // These nodes disappear once Blazor renders. Never overwrite the running app.
    const loading = document.getElementById('startup-loading');
    if (loading) loading.textContent = text[0];
    document.getElementById('startup-error').textContent = text[1];
    document.getElementById('startup-reload').textContent = text[2];
    window.runninghillErrors?.refresh();
  };
  window.runninghillLanguage = {
    text: message => messages[document.documentElement.lang]?.[labels.indexOf(message)] || message,
    get: () => {
      try { return normalize(localStorage.getItem('runninghill.language')); }
      catch { return 'en-ZA'; } // Private browsing/storage restrictions must not prevent startup.
    },
    set: value => {
      const language = normalize(value);
      try { localStorage.setItem('runninghill.language', language); } catch { /* Session still works. */ }
      apply(language);
    }
  };
  apply(window.runninghillLanguage.get());
})();
"""
    return {
        ROOT / "src/Runninghill.Contracts/AppText.Keys.g.cs": source,
        ROOT / "src/Clients/Runninghill.Web/wwwroot/localization.js": javascript,
    }


def main():
    """Fail the check if a translation, placeholder, or generated artifact is missing."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true")
    args = parser.parse_args()
    catalogs = {language: read(suffix) for language, suffix in LANGUAGES.items()}
    english = catalogs["en-ZA"]
    assert len(set(english.values())) == len(english), "English messages must be unique"
    for path in (ROOT / "src").rglob("*"):
        if path.suffix not in (".cs", ".razor") or "obj" in path.parts or "bin" in path.parts:
            continue
        for literal in re.findall(r'\bT\(("(?:[^"\\]|\\.)*")\)', path.read_text(encoding="utf-8")):
            message = json.loads(literal)
            assert message in english.values(), f"Uncatalogued message: {path.name}: {message}"
    for path in (ROOT / "src/Clients/Runninghill.Maui").glob("*.xaml"):
        for key in re.findall(r"loc:Translate Key=(Text_[a-z0-9]+)", path.read_text(encoding="utf-8")):
            assert key in english, f"Unknown XAML resource: {path.name}/{key}"
    for language, entries in catalogs.items():
        assert entries.keys() == english.keys(), f"Missing/extra translations: {language}"
        for key, value in entries.items():
            assert value and value.strip(), f"Empty translation: {language}/{key}"
            # Keep format specifiers and argument indices intact; their order can change.
            assert sorted(re.findall(r"\{\d+[^}]*\}", value)) == sorted(re.findall(r"\{\d+[^}]*\}", english[key])), f"Changed placeholders: {language}/{key}"
    for path, content in generated_files(catalogs).items():
        if args.generate:
            path.write_text(content, encoding="utf-8")
        else:
            assert path.read_text(encoding="utf-8") == content, f"Regenerate {path.name} using --generate"
    print(f"Verified {len(english)} messages in each of {len(catalogs)} languages.")


if __name__ == "__main__":
    main()
