// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Runninghill.Database;

#nullable disable

namespace Runninghill.Database.Migrations.MySql
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Runninghill.Database.SchemaRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("schema_info", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Version = 3
                        });
                });

            modelBuilder.Entity("Runninghill.Database.SentenceRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("char(36)")
                        .HasColumnName("request_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4050)
                        .HasColumnType("varchar(4050)")
                        .HasColumnName("text");

                    b.Property<string>("WordIds")
                        .IsRequired()
                        .HasMaxLength(1050)
                        .HasColumnType("varchar(1050)")
                        .HasColumnName("word_ids");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("sentences_request_id");

                    b.ToTable("sentences", (string)null);
                });

            modelBuilder.Entity("Runninghill.Database.WordRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedWord")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("normalized_word")
                        .HasAnnotation("MySQL:Collation", "utf8mb4_bin");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedWord", "Type")
                        .IsUnique()
                        .HasDatabaseName("words_normalized_type");

                    b.HasIndex("Type", "Id")
                        .HasDatabaseName("words_type_id");

                    b.ToTable("words", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
