using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.IdentityModel.Tokens;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;
using Runninghill.Application;
using Runninghill.Contracts;
using Runninghill.Database;
using Runninghill.Service;

// The slim host loads only the features we use. This keeps native startup and memory costs low.
var builder = WebApplication.CreateSlimBuilder(args);
if (builder.Environment.IsDevelopment())
{
    // Generated by scripts/dev.py, ignored by Git and Docker, and never loaded in production.
    if (builder.Configuration["RUNNINGHILL_LOCAL_DEBUG"] == "1")
        builder.Configuration.AddJsonFile("appsettings.Development.local.json", optional: false)
            .AddEnvironmentVariables().AddCommandLine(args);
    builder.Services.AddCors(options => options.AddPolicy("LocalDebugger", policy => policy
        .WithOrigins("http://localhost:5182", "http://127.0.0.1:5182")
        .WithMethods("GET", "POST", "PUT", "DELETE").WithHeaders("Authorization", "Content-Type").WithExposedHeaders("X-Request-ID")));
}
// Migration mode needs only database settings. It never opens HTTP listeners or requires
// an access-token issuer, so deployment tooling can use a separate DDL credential.
if (args.Contains("--migrate-database"))
{
    builder.Services.AddCollectionDatabase(_ => DatabaseSettings.Parse(
        builder.Configuration["Database:Provider"], builder.Configuration.GetConnectionString("Runninghill")));
    await using var migrationHost = builder.Build();
    await migrationHost.Services.GetRequiredService<DatabaseMigrator>().MigrateAsync();
    return;
}
builder.Services.AddSingleton(services => ServiceConfiguration.Load(
    services.GetRequiredService<IConfiguration>(), services.GetRequiredService<IHostEnvironment>()));
builder.Logging.ClearProviders();
builder.Logging.AddJsonConsole();
// Export telemetry only when a collector is configured; local development needs no collector.
var exportTelemetry = !string.IsNullOrWhiteSpace(builder.Configuration["OTEL_EXPORTER_OTLP_ENDPOINT"]);
builder.Services.AddOpenTelemetry()
    .ConfigureResource(resource => resource.AddService("Runninghill.Service"))
    .WithTracing(tracing =>
    {
        tracing.AddAspNetCoreInstrumentation().AddSource("Npgsql");
        if (exportTelemetry) tracing.AddOtlpExporter();
    })
    .WithMetrics(metrics =>
    {
        metrics.AddAspNetCoreInstrumentation().AddMeter("Microsoft.AspNetCore.Server.Kestrel", "Microsoft.EntityFrameworkCore", "Npgsql");
        if (exportTelemetry) metrics.AddOtlpExporter();
    });
// Give in-flight work time to finish when the host shuts down.
builder.Services.Configure<HostOptions>(options => options.ShutdownTimeout = TimeSpan.FromSeconds(30));
builder.Services.ConfigureHttpJsonOptions(options => options.SerializerOptions.TypeInfoResolverChain.Insert(0, ApiJsonContext.Default));
builder.Services.AddCollectionDatabase(services => services.GetRequiredService<ServiceConfiguration>().Database);
builder.Services.AddTransient<IRunninghillApplication, RunninghillApplication>();
builder.Services.AddTransient<WordCollection>();
// Bound request buffering before JSON is parsed. A sentence contains at most 50 word IDs.
builder.WebHost.ConfigureKestrel(options => options.Limits.MaxRequestBodySize = 16 * 1024);
// Authentication checks who sent the token; authorization below checks what they may do.
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer();
builder.Services.AddOptions<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme).Configure<ServiceConfiguration>((options, configuration) =>
{
    options.Audience = configuration.Audience;
    options.MapInboundClaims = false;
    if (!string.IsNullOrWhiteSpace(configuration.Authority))
        options.Authority = configuration.Authority;
    // The shared signing key is a local-development shortcut. Configuration rejects it in production.
    else
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true, ValidIssuer = "runninghill-development",
            ValidateAudience = true, ValidAudience = configuration.Audience,
            ValidateLifetime = true, ClockSkew = TimeSpan.FromSeconds(30),
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(configuration.DevelopmentSigningKey!)),
            ValidAlgorithms = [SecurityAlgorithms.HmacSha256]
        };
});
builder.Services.AddAuthorizationBuilder().AddPolicy("status.read", policy =>
    policy.RequireAuthenticatedUser().RequireAssertion(context => ScopePermissions.HasScope(context.User, "status.read")));
foreach (var scope in new[] { "words.read", "words.write", "sentences.read", "sentences.write" })
    builder.Services.AddAuthorizationBuilder().AddPolicy(scope, policy =>
        policy.RequireAuthenticatedUser().RequireAssertion(context => ScopePermissions.HasScope(context.User, scope)));
builder.Services.AddGrpc(options => options.EnableDetailedErrors = false);
builder.Services.AddProblemDetails(options => options.CustomizeProblemDetails = ApiErrors.DescribeProblem);
builder.Services.AddExceptionHandler<ApiErrors>();
builder.Services.AddRequestTimeouts();
// Reject excess work immediately instead of letting a waiting queue grow and exhaust memory.
builder.Services.AddRateLimiter(options =>
{
    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
    options.AddConcurrencyLimiter("api", limits => { limits.PermitLimit = 64; limits.QueueLimit = 0; });
});
builder.Services.AddHealthChecks().AddCheck<DatabaseHealthCheck>("database", tags: ["ready"], timeout: TimeSpan.FromSeconds(6));

var app = builder.Build();
// Resolve validated settings before opening listeners; never silently use a fallback.
_ = app.Services.GetRequiredService<ServiceConfiguration>();
_ = app.Services.GetRequiredService<DatabaseSettings>();
// Keep the same reference in HTTP headers, error bodies, and server logs.
app.Use((context, next) =>
{
    // OnStarting runs after an exception handler has cleared/replaced a failed response.
    context.Response.OnStarting(static state =>
    {
        var requestContext = (HttpContext)state;
        requestContext.Response.Headers["X-Request-ID"] = requestContext.TraceIdentifier;
        return Task.CompletedTask;
    }, context);
    // There is no work after the next handler, so return its task without another async wrapper.
    return next(context);
});
// Keep diagnostics for real service failures. Expected validation errors should not flood
// error logs or count as outages merely because they use the same friendly error handler.
app.UseExceptionHandler(new ExceptionHandlerOptions
{
    SuppressDiagnosticsCallback = context => context.Exception is CollectionException or BadHttpRequestException
});
if (app.Environment.IsDevelopment())
    app.UseCors("LocalDebugger");
// Binding failures and rejected requests also get readable JSON, not an empty error page.
app.UseStatusCodePages(async status =>
{
    var code = status.HttpContext.Response.StatusCode;
    await Results.Problem(statusCode: code, title: "The request could not be completed.",
        detail: code switch
        {
            400 => "Check the JSON fields and page position, then try again.",
            413 => "This request is too large. Use one word or at most 50 words in a sentence.",
            415 => "Send this request as application/json.",
            429 => "The service is busy. Wait a few seconds and try again.",
            _ => "Check your access and service address. Share the request reference if the problem continues."
        }).ExecuteAsync(status.HttpContext);
});
app.UseAuthentication();
app.UseAuthorization();
app.UseRateLimiter();
app.UseRequestTimeouts();
// Live means the process is running. Ready also means it can use the database.
// Keeping these separate prevents a database outage from causing endless service restarts.
app.MapHealthChecks("/health/live", new HealthCheckOptions { Predicate = _ => false });
app.MapHealthChecks("/health/ready", new HealthCheckOptions { Predicate = check => check.Tags.Contains("ready") });
app.MapGet("/api/status", async (IRunninghillApplication application, HttpContext context, ILogger<Program> logger, CancellationToken cancellationToken) =>
{
    try
    {
        return Results.Ok(new StatusResponse(await application.GetStatusAsync(cancellationToken)));
    }
    catch (ApplicationUnavailableException)
    {
        logger.LogWarning("Database unavailable for status request. Request reference: {RequestId}", context.TraceIdentifier);
        return Results.Problem(statusCode: StatusCodes.Status503ServiceUnavailable,
            title: "The service cannot reach its data right now.",
            detail: "Please try again shortly. If this continues, share the request reference with support.");
    }
}).RequireAuthorization("status.read").RequireRateLimiting("api").WithRequestTimeout(TimeSpan.FromSeconds(10));
app.MapGrpcService<ApplicationGrpcService>().RequireAuthorization("status.read").RequireRateLimiting("api");
app.MapWordEndpoints();
app.Run();

public partial class Program;
