// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Runninghill.Database;

#nullable disable

namespace Runninghill.Database.Migrations.Sqlite
{
    /// <summary>
    /// Records the Sqlite EF model after adding the initial collection tables; used by migration
    /// tooling.
    /// </summary>
    [DbContext(typeof(SqliteContext))]
    [Migration("20261008141610_InitialCollection")]
    partial class InitialCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Runninghill.Database.SchemaRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("schema_info", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Version = 2
                        });
                });

            modelBuilder.Entity("Runninghill.Database.SentenceRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4050)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("WordIds")
                        .IsRequired()
                        .HasMaxLength(1050)
                        .HasColumnType("TEXT")
                        .HasColumnName("word_ids");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("sentences_request_id");

                    b.ToTable("sentences", (string)null);
                });

            modelBuilder.Entity("Runninghill.Database.WordRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Id")
                        .HasDatabaseName("words_type_id");

                    b.HasIndex("Word", "Type")
                        .IsUnique()
                        .HasDatabaseName("words_word_type");

                    b.ToTable("words", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
